#!/usr/bin/env python3
"""
NotiFetch v2.1.0 — Google Play Store Submission Guide
Comprehensive PDF document covering all steps for Play Store submission.
"""

import sys
import os

# Add PDF skill scripts to path
PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT       = colors.HexColor('#502eb6')
TEXT_PRIMARY  = colors.HexColor('#1d1c1a')
TEXT_MUTED    = colors.HexColor('#78736d')
BG_SURFACE   = colors.HexColor('#dedad5')
BG_PAGE      = colors.HexColor('#efedea')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf'))  # Fallback
pdfmetrics.registerFont(TTFont('Carlito', '/usr/share/fonts/truetype/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('CarlitoBold', '/usr/share/fonts/truetype/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSerif', '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
registerFontFamily('Carlito', normal='Carlito', bold='CarlitoBold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('LiberationSans', normal='LiberationSans', bold='LiberationSans')

# ━━ Page Setup ━━
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Styles ━━
title_style = ParagraphStyle(
    name='DocTitle', fontName='Carlito', fontSize=28,
    leading=36, alignment=TA_CENTER, textColor=ACCENT,
    spaceAfter=12
)
subtitle_style = ParagraphStyle(
    name='DocSubtitle', fontName='Carlito', fontSize=16,
    leading=22, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceAfter=24
)
h1_style = ParagraphStyle(
    name='H1', fontName='Carlito', fontSize=20,
    leading=28, textColor=ACCENT, spaceBefore=18, spaceAfter=10
)
h2_style = ParagraphStyle(
    name='H2', fontName='Carlito', fontSize=15,
    leading=22, textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8
)
h3_style = ParagraphStyle(
    name='H3', fontName='Carlito', fontSize=12,
    leading=18, textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6
)
body_style = ParagraphStyle(
    name='Body', fontName='Carlito', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceAfter=8
)
body_left_style = ParagraphStyle(
    name='BodyLeft', fontName='Carlito', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceAfter=8
)
bullet_style = ParagraphStyle(
    name='Bullet', fontName='Carlito', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=20, spaceAfter=4, bulletIndent=8
)
code_style = ParagraphStyle(
    name='Code', fontName='DejaVuSans', fontSize=9,
    leading=14, alignment=TA_LEFT, textColor=colors.HexColor('#2d2d2d'),
    backColor=colors.HexColor('#f5f5f5'), leftIndent=12,
    rightIndent=12, spaceBefore=6, spaceAfter=6,
    borderPadding=(6, 6, 6, 6)
)
note_style = ParagraphStyle(
    name='Note', fontName='Carlito', fontSize=10,
    leading=15, alignment=TA_LEFT, textColor=colors.HexColor('#b71c1c'),
    leftIndent=12, spaceBefore=6, spaceAfter=6,
    borderPadding=(6, 6, 6, 6), backColor=colors.HexColor('#fff3e0')
)
header_cell_style = ParagraphStyle(
    name='HeaderCell', fontName='Carlito', fontSize=10,
    leading=14, textColor=colors.white, alignment=TA_CENTER
)
cell_style = ParagraphStyle(
    name='Cell', fontName='Carlito', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_LEFT
)
cell_center_style = ParagraphStyle(
    name='CellCenter', fontName='Carlito', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_CENTER
)

# ━━ TOC Template ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

import hashlib

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]

# ━━ Helper Functions ━━
def make_table(data, col_widths, has_header=True):
    table = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ]
    if has_header:
        style_cmds.append(('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR))
        style_cmds.append(('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT))
        for i in range(1, len(data)):
            bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
            style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    table.setStyle(TableStyle(style_cmds))
    return table

def hr():
    return HRFlowable(width="100%", thickness=0.5, color=TEXT_MUTED, spaceAfter=12, spaceBefore=12)

# ━━ Build Document ━━
output_path = "/home/z/my-project/download/NotiFetch-PlayStore-Submission-Guide.pdf"

doc = TocDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title="NotiFetch Play Store Submission Guide",
    author="Z.ai",
    creator="Z.ai",
    subject="Step-by-step guide for publishing NotiFetch v2.1.0 to Google Play Store"
)

story = []

# ━━ Title Page ━━
story.append(Spacer(1, 2 * inch))
story.append(Paragraph("<b>NotiFetch</b>", title_style))
story.append(Spacer(1, 12))
story.append(Paragraph("<b>Google Play Store Submission Guide</b>", subtitle_style))
story.append(Spacer(1, 24))
story.append(Paragraph("Version 2.1.0", ParagraphStyle(
    name='VersionText', fontName='Carlito', fontSize=14,
    leading=20, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 8))
story.append(Paragraph("versionCode: 3 | versionName: 2.1.0", ParagraphStyle(
    name='VersionDetail', fontName='Carlito', fontSize=11,
    leading=16, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 36))
story.append(Paragraph("Delivery Driver Notification Aggregator", ParagraphStyle(
    name='Tagline', fontName='Carlito', fontSize=12,
    leading=18, alignment=TA_CENTER, textColor=TEXT_PRIMARY
)))
story.append(Spacer(1, 12))
story.append(Paragraph("Application ID: com.notifetch.app", ParagraphStyle(
    name='AppId', fontName='DejaVuSans', fontSize=10,
    leading=16, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 48))
story.append(Paragraph("SHA-256: 81:97:95:57:6B:2F:1C:94:D2:7A:6B:63:E2:3C:7C:C7:D8:58:50:CB:CA:A1:E5:00:7A:23:BB:3B:44:DD:AB:FE", ParagraphStyle(
    name='SHA256', fontName='DejaVuSans', fontSize=7.5,
    leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED
)))
story.append(Spacer(1, 12))
story.append(Paragraph("Web: https://d2-liart-nine.vercel.app", ParagraphStyle(
    name='WebURL', fontName='Carlito', fontSize=10,
    leading=16, alignment=TA_CENTER, textColor=ACCENT
)))
story.append(Paragraph("Privacy: https://d2-liart-nine.vercel.app/privacy", ParagraphStyle(
    name='PrivURL', fontName='Carlito', fontSize=10,
    leading=16, alignment=TA_CENTER, textColor=ACCENT
)))
story.append(Paragraph("Terms: https://d2-liart-nine.vercel.app/terms", ParagraphStyle(
    name='TermsURL', fontName='Carlito', fontSize=10,
    leading=16, alignment=TA_CENTER, textColor=ACCENT
)))
story.append(PageBreak())

# ━━ Table of Contents ━━
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle(name='TOCHeading1', fontSize=13, leftIndent=20, fontName='Carlito',
                   spaceBefore=8, spaceAfter=4, leading=20),
    ParagraphStyle(name='TOCHeading2', fontSize=11, leftIndent=40, fontName='Carlito',
                   spaceBefore=4, spaceAfter=2, leading=16),
]
story.append(Paragraph("<b>Table of Contents</b>", ParagraphStyle(
    name='TOCTitle', fontName='Carlito', fontSize=20,
    leading=28, textColor=ACCENT, spaceAfter=18
)))
story.append(toc)
story.append(PageBreak())

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 1: Pre-Submission Checklist
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("1. Pre-Submission Checklist", h1_style))

story.append(Paragraph(
    "Before submitting NotiFetch to the Google Play Store, every item in this checklist must be completed. "
    "Google Play enforces strict policies on notification access apps, data safety declarations, and legal compliance. "
    "Missing any item below may result in app rejection or suspension. Each item is marked with its priority level "
    "and the section of this guide where detailed instructions can be found.",
    body_style
))

checklist_data = [
    [Paragraph('<b>Item</b>', header_cell_style),
     Paragraph('<b>Status</b>', header_cell_style),
     Paragraph('<b>Priority</b>', header_cell_style),
     Paragraph('<b>Section</b>', header_cell_style)],
    [Paragraph('Firebase project created + google-services.json', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 2', cell_center_style)],
    [Paragraph('Keystore passwords saved securely', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 3', cell_center_style)],
    [Paragraph('Signed AAB generated', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 3', cell_center_style)],
    [Paragraph('Google Play Developer account', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 4', cell_center_style)],
    [Paragraph('Privacy Policy URL live', cell_style),
     Paragraph('LIVE', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 7', cell_center_style)],
    [Paragraph('Terms of Service URL live', cell_style),
     Paragraph('LIVE', cell_center_style),
     Paragraph('CRITICAL', cell_center_style),
     Paragraph('Section 7', cell_center_style)],
    [Paragraph('Data Safety form completed', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('HIGH', cell_center_style),
     Paragraph('Section 6', cell_center_style)],
    [Paragraph('Content Rating questionnaire', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('HIGH', cell_center_style),
     Paragraph('Section 6', cell_center_style)],
    [Paragraph('Store listing content prepared', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('HIGH', cell_center_style),
     Paragraph('Section 5', cell_center_style)],
    [Paragraph('App screenshots captured', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('MEDIUM', cell_center_style),
     Paragraph('Section 5', cell_center_style)],
    [Paragraph('Feature graphic designed', cell_style),
     Paragraph('PENDING', cell_center_style),
     Paragraph('MEDIUM', cell_center_style),
     Paragraph('Section 5', cell_center_style)],
]

story.append(Spacer(1, 12))
story.append(make_table(checklist_data, [AVAILABLE_WIDTH*0.42, AVAILABLE_WIDTH*0.15, AVAILABLE_WIDTH*0.15, AVAILABLE_WIDTH*0.15]))
story.append(Spacer(1, 12))

story.append(Paragraph(
    "Items marked CRITICAL will block your submission entirely. Items marked HIGH may cause rejection "
    "during Google Play review. Items marked MEDIUM are recommended but may not block initial submission. "
    "Note that Privacy Policy and Terms of Service URLs are already live on your Vercel deployment, "
    "which satisfies two of the most common rejection reasons for notification-access apps.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 2: Firebase Project Setup
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("2. Firebase Project Setup", h1_style))

story.append(Paragraph(
    "NotiFetch uses Firebase for three features: Anonymous Authentication (for cross-device sync), "
    "Firebase Cloud Messaging (for push notifications), and Firebase Analytics (for usage insights). "
    "Currently, the google-services.json in the Android project is a placeholder and must be replaced "
    "with a real Firebase project configuration. The core notification listener feature works without "
    "Firebase, but cloud sync, push notifications, and analytics require proper Firebase setup.",
    body_style
))

story.append(add_heading("2.1 Create Firebase Project", h2_style, level=1))
story.append(Paragraph("Follow these exact steps to set up Firebase for NotiFetch:", body_style))

firebase_steps = [
    "Go to https://console.firebase.google.com and sign in with your Google account",
    "Click 'Add Project' and enter the project name: <b>NotiFetch</b>",
    "Disable Google Analytics for now (you can enable it later) and click Create Project",
    "Once created, click the Android icon to add an Android app",
    "Enter the Android package name: <b>com.notifetch.app</b>",
    "Enter the app nickname: <b>NotiFetch</b>",
    "Enter the SHA-1 and SHA-256 fingerprints from your keystore",
    "Click 'Register App'",
    "Download the <b>google-services.json</b> file",
    "Replace the placeholder file at: notifetch-android/app/google-services.json",
    "Continue through the remaining setup steps (add Firebase SDK - already configured in build.gradle.kts)",
]
for i, step in enumerate(firebase_steps, 1):
    story.append(Paragraph(
        "<b>Step %d.</b> %s" % (i, step), bullet_style
    ))

story.append(add_heading("2.2 Add SHA-256 Fingerprint to Firebase", h2_style, level=1))
story.append(Paragraph(
    "Your keystore SHA-256 fingerprint must be added to the Firebase project for Authentication "
    "and Dynamic Links to work. This fingerprint is already generated and stored in your signing credentials:",
    body_style
))
story.append(Paragraph(
    "SHA-256: 81:97:95:57:6B:2F:1C:94:D2:7A:6B:63:E2:3C:7C:C7:D8:58:50:CB:CA:A1:E5:00:7A:23:BB:3B:44:DD:AB:FE",
    code_style
))
story.append(Paragraph(
    "To add it in Firebase Console: Go to Project Settings > Your Apps > NotiFetch > "
    "SHA certificate fingerprints > Add fingerprint. Paste the SHA-256 value above. "
    "This must match the keystore you use to sign the AAB, or Firebase Auth will reject all sign-in attempts.",
    body_style
))

story.append(add_heading("2.3 Enable Firebase Services", h2_style, level=1))

firebase_services_data = [
    [Paragraph('<b>Service</b>', header_cell_style),
     Paragraph('<b>Firebase Console Path</b>', header_cell_style),
     Paragraph('<b>Required</b>', header_cell_style)],
    [Paragraph('Anonymous Auth', cell_style),
     Paragraph('Authentication > Sign-in method > Anonymous', cell_style),
     Paragraph('Yes', cell_center_style)],
    [Paragraph('Cloud Messaging', cell_style),
     Paragraph('Project Settings > Cloud Messaging', cell_style),
     Paragraph('Yes', cell_center_style)],
    [Paragraph('Analytics', cell_style),
     Paragraph('Analytics (enable in Project Settings)', cell_style),
     Paragraph('Recommended', cell_center_style)],
    [Paragraph('Crashlytics', cell_style),
     Paragraph('Crashlytics (enable in sidebar)', cell_style),
     Paragraph('Recommended', cell_center_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(firebase_services_data, [AVAILABLE_WIDTH*0.25, AVAILABLE_WIDTH*0.50, AVAILABLE_WIDTH*0.18]))

story.append(add_heading("2.4 Download and Replace google-services.json", h2_style, level=1))
story.append(Paragraph(
    "After registering the Android app in Firebase, download the google-services.json file and "
    "place it at the following path in your Android project, replacing the placeholder:",
    body_style
))
story.append(Paragraph(
    "notifetch-android/app/google-services.json",
    code_style
))
story.append(Paragraph(
    "The placeholder file currently contains dummy values (project_id: notifetch-placeholder, "
    "api_key: PLACEHOLDER_API_KEY). The Google Services Gradle plugin will validate this file "
    "during build, and a real Firebase config is required for Authentication and FCM to function. "
    "After replacing the file, sync your Gradle project in Android Studio before building.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 3: Building the Signed AAB
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("3. Building the Signed AAB", h1_style))

story.append(Paragraph(
    "Google Play Store requires an Android App Bundle (AAB) file for new app submissions. "
    "The AAB contains compiled code and resources for all device configurations, and Google Play "
    "uses it to generate optimized APKs for each user device. The AAB must be signed with your "
    "release keystore. Your project is already configured with a release signing configuration "
    "in build.gradle.kts, but you need to set the keystore passwords before building.",
    body_style
))

story.append(add_heading("3.1 Keystore Configuration", h2_style, level=1))

keystore_data = [
    [Paragraph('<b>Property</b>', header_cell_style),
     Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Keystore Path', cell_style),
     Paragraph('twa/keystore.jks (relative to project root)', cell_style)],
    [Paragraph('Key Alias', cell_style),
     Paragraph('notifetch', cell_style)],
    [Paragraph('SHA-256', cell_style),
     Paragraph('81:97:95:57:6B:2F:1C:94:D2:7A:6B:63:E2:3C:7C:C7:D8:58:50:CB:CA:A1:E5:00:7A:23:BB:3B:44:DD:AB:FE', cell_style)],
    [Paragraph('Store Password', cell_style),
     Paragraph('Set via NOTIFETCH_STORE_PASSWORD env var', cell_style)],
    [Paragraph('Key Password', cell_style),
     Paragraph('Set via NOTIFETCH_KEY_PASSWORD env var', cell_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(keystore_data, [AVAILABLE_WIDTH*0.30, AVAILABLE_WIDTH*0.65]))

story.append(Paragraph(
    "The signing configuration in build.gradle.kts reads passwords from environment variables "
    "NOTIFETCH_STORE_PASSWORD and NOTIFETCH_KEY_PASSWORD. If these are not set, the build falls back "
    "to the hardcoded value 'changeme_notifetch_store_2024'. You must ensure the passwords you set "
    "match those used when generating the keystore, or the build will fail with a keystore tampering error.",
    body_style
))

story.append(add_heading("3.2 Build Commands", h2_style, level=1))
story.append(Paragraph(
    "Open a terminal in the notifetch-android directory and run the following commands to generate "
    "the signed AAB. Make sure you have Android Studio or the Android SDK command-line tools installed, "
    "and that ANDROID_HOME is set to your SDK path.",
    body_style
))

story.append(Paragraph(
    "# Option 1: Set passwords as environment variables (RECOMMENDED)<br/>"
    "export NOTIFETCH_STORE_PASSWORD=your_store_password<br/>"
    "export NOTIFETCH_KEY_PASSWORD=your_key_password<br/><br/>"
    "# Build the release AAB<br/>"
    "cd notifetch-android<br/>"
    "./gradlew bundleRelease<br/><br/>"
    "# The AAB will be generated at:<br/>"
    "# app/build/outputs/bundle/release/app-release.aab",
    code_style
))

story.append(Paragraph(
    "# Option 2: Build from Android Studio<br/>"
    "# 1. Open the notifetch-android project in Android Studio<br/>"
    "# 2. Go to Build > Generate Signed Bundle / APK<br/>"
    "# 3. Select 'Android App Bundle'<br/>"
    "# 4. Choose the keystore at twa/keystore.jks<br/>"
    "# 5. Enter the key alias: notifetch<br/>"
    "# 6. Enter the store and key passwords<br/>"
    "# 7. Select 'release' build variant<br/>"
    "# 8. Click Finish",
    code_style
))

story.append(add_heading("3.3 Verify the AAB", h2_style, level=1))
story.append(Paragraph(
    "After building, verify the AAB file before uploading to Play Store. Check that the file size is "
    "reasonable (typically 3-8 MB for a Compose app), the signing certificate matches your keystore, "
    "and the version information is correct:",
    body_style
))
story.append(Paragraph(
    "# Check AAB file size<br/>"
    "ls -la app/build/outputs/bundle/release/app-release.aab<br/><br/>"
    "# Verify signing certificate matches<br/>"
    "# The SHA-256 should match: 81:97:95:57:6B:2F:1C:94:D2:7A:6B:63:...<br/>"
    "keytool -printcert -jarfile app/build/outputs/bundle/release/app-release.aab<br/><br/>"
    "# Check bundle contents<br/>"
    "bundletool dump manifest --bundle=app-release.aab",
    code_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 4: Google Play Console Setup
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("4. Google Play Console Setup", h1_style))

story.append(add_heading("4.1 Create Developer Account", h2_style, level=1))
story.append(Paragraph(
    "To publish apps on Google Play, you need a Google Play Developer account. This is a one-time "
    "registration that costs $25 USD. Go to https://play.google.com/console/signup and follow the "
    "registration process. You will need a Google account, identity verification (government ID), "
    "and a credit card for the registration fee. The verification process typically takes 1-3 business days, "
    "though it can be faster. Once registered, you will have access to the Google Play Console where "
    "you can create and manage your app listings.",
    body_style
))

story.append(add_heading("4.2 Create App Listing", h2_style, level=1))
story.append(Paragraph(
    "Once your developer account is active, create a new app listing in Google Play Console. "
    "Follow these steps carefully, as some fields cannot be changed after the first release:",
    body_style
))

app_creation_steps = [
    "Click 'Create app' in the Play Console dashboard",
    "App name: <b>NotiFetch</b>",
    "Default language: <b>English (United States)</b>",
    "Free or paid: <b>Free</b>",
    "App declarations: Accept the Play App Signing Terms, US export laws compliance",
    "App category: <b>Productivity</b>",
    "Tags: Notification manager, Delivery driver tools, Earnings tracker",
]
for i, step in enumerate(app_creation_steps, 1):
    story.append(Paragraph("Step %d: %s" % (i, step), bullet_style))

story.append(add_heading("4.3 App Signing (Google Play App Signing)", h2_style, level=1))
story.append(Paragraph(
    "Google Play App Signing is mandatory for all new apps. When you upload your first AAB, "
    "Google will enroll your app in Play App Signing. This means Google manages your app signing key "
    "and generates optimized APKs from your AAB. Your original keystore is used as the 'upload key' "
    "for signing AABs you upload to Play Console. If you lose your upload key, you can request a reset "
    "from Google. However, if you opted out of Play App Signing and lost your signing key, your app "
    "cannot be updated. Always opt in to Play App Signing for safety.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 5: Store Listing Content
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("5. Store Listing Content", h1_style))

story.append(add_heading("5.1 App Title and Short Description", h2_style, level=1))

story.append(Paragraph("<b>App Title (max 30 characters):</b>", body_style))
story.append(Paragraph("NotiFetch - Delivery Tracker", body_left_style))

story.append(Paragraph("<b>Short Description (max 80 characters):</b>", body_style))
story.append(Paragraph(
    "Aggregate delivery notifications. Track orders and earnings across all platforms.",
    body_left_style
))

story.append(add_heading("5.2 Full Description", h2_style, level=1))
story.append(Paragraph(
    "NotiFetch is a personal notification aggregator designed specifically for delivery drivers and gig workers. "
    "It captures and organizes notifications from your delivery partner apps so you never miss an order, "
    "can track your earnings across platforms, and manage your workday efficiently.",
    body_style
))
story.append(Paragraph(
    "WORKS WITH 55+ DELIVERY PLATFORMS: NotiFetch recognizes notifications from Swiggy, Zomato, Amazon Flex, "
    "Zepto, Blinkit, Uber, DoorDash, Rapido, Porter, Delhivery, Shadowfax, and many more delivery and "
    "driver apps across India and globally. See the full list in the app's Settings screen.",
    body_style
))
story.append(Paragraph(
    "KEY FEATURES:",
    body_style
))
features_list = [
    "Smart Notification Capture - Automatically captures order notifications from delivery partner apps using Android's NotificationListenerService",
    "Earnings Tracking - See your earnings across all platforms in one unified view",
    "Platform Customization - Rename any platform to your preferred name for quick identification",
    "Per-Platform Filters - Choose which delivery apps to monitor; turn off platforms you don't use",
    "Cross-Device Sync - Sync your notification history across devices with secure cloud backup",
    "Data Privacy First - Your data stays on your device. We never access personal messages, banking, or social media notifications",
    "30-Day Auto-Delete - Captured notifications are automatically deleted after 30 days",
    "Data Export and Deletion - Export or delete all your data anytime (DPDP Act 2023 and GDPR compliant)",
    "Dark Mode - Easy on the eyes during late-night delivery shifts",
]
for feature in features_list:
    story.append(Paragraph(feature, bullet_style))

story.append(add_heading("5.3 Screenshots Requirements", h2_style, level=1))

screenshot_data = [
    [Paragraph('<b>Screenshot Type</b>', header_cell_style),
     Paragraph('<b>Min</b>', header_cell_style),
     Paragraph('<b>Max</b>', header_cell_style),
     Paragraph('<b>Dimensions</b>', header_cell_style)],
    [Paragraph('Phone screenshots', cell_style),
     Paragraph('4', cell_center_style),
     Paragraph('8', cell_center_style),
     Paragraph('16:9 or 9:16, min 320px', cell_style)],
    [Paragraph('Tablet screenshots', cell_style),
     Paragraph('0', cell_center_style),
     Paragraph('8', cell_center_style),
     Paragraph('16:9 or 9:16', cell_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(screenshot_data, [AVAILABLE_WIDTH*0.30, AVAILABLE_WIDTH*0.10, AVAILABLE_WIDTH*0.10, AVAILABLE_WIDTH*0.40]))

story.append(Paragraph(
    "Recommended screenshots to capture on a real device or emulator (do NOT show any platform logos "
    "or brand assets in screenshots for legal safety):",
    body_style
))
screenshot_recs = [
    "Home screen with sample notifications (use generic names, not real brand names in screenshots)",
    "Notification detail view showing order information",
    "Settings screen showing platform customization feature",
    "Consent screen showing data privacy commitments",
    "Profile screen with data rights section visible",
    "Dark mode version of the home screen",
    "Search/filter functionality",
    "Platform rename dialog",
]
for rec in screenshot_recs:
    story.append(Paragraph(rec, bullet_style))

story.append(add_heading("5.4 Feature Graphic", h2_style, level=1))
story.append(Paragraph(
    "The feature graphic is a 1024x500 PNG that appears at the top of your Play Store listing. "
    "It should showcase the app name 'NotiFetch' prominently with a tagline like 'All your delivery "
    "notifications in one place'. Use a clean design with the app's primary color scheme. Do not "
    "include any delivery platform logos or brand assets. Consider using a device mockup showing "
    "the app interface with generic/placeholder data. The graphic should be visually clear and readable "
    "even at small sizes on mobile devices.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 6: Data Safety and Content Rating
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("6. Data Safety and Content Rating", h1_style))

story.append(add_heading("6.1 Google Play Data Safety Declarations", h2_style, level=1))
story.append(Paragraph(
    "Google Play requires all apps to declare what user data they collect, how it is used, and whether "
    "it is shared. This is a critical compliance requirement that directly affects your app's visibility "
    "and trust. For NotiFetch, you must be transparent about the notification data the app reads. "
    "The Data Safety form is in Play Console > App Content > Data Safety. Here are the exact declarations "
    "you should make:",
    body_style
))

data_safety_data = [
    [Paragraph('<b>Data Type</b>', header_cell_style),
     Paragraph('<b>Collected</b>', header_cell_style),
     Paragraph('<b>Shared</b>', header_cell_style),
     Paragraph('<b>Purpose</b>', header_cell_style),
     Paragraph('<b>Encrypted</b>', header_cell_style),
     Paragraph('<b>Deletable</b>', header_cell_style)],
    [Paragraph('App activity (notifications)', cell_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('No', cell_center_style),
     Paragraph('App functionality', cell_center_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('Yes', cell_center_style)],
    [Paragraph('App info and performance', cell_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('No', cell_center_style),
     Paragraph('Analytics', cell_center_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('Yes', cell_center_style)],
    [Paragraph('Device or other IDs', cell_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('No', cell_center_style),
     Paragraph('App functionality', cell_center_style),
     Paragraph('Yes', cell_center_style),
     Paragraph('Yes', cell_center_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(data_safety_data, [AVAILABLE_WIDTH*0.22, AVAILABLE_WIDTH*0.12, AVAILABLE_WIDTH*0.10, AVAILABLE_WIDTH*0.20, AVAILABLE_WIDTH*0.13, AVAILABLE_WIDTH*0.13]))

story.append(Paragraph(
    "Important: You must also answer 'Yes' to 'Does your app access notifications?' and explain that "
    "NotiFetch uses NotificationListenerService to read delivery partner app notifications only, with "
    "the user's explicit permission. This is a required disclosure for apps using this API. Be specific "
    "that the app only reads notifications from delivery/driver apps and never accesses personal messages, "
    "banking apps, or social media notifications. This transparency is critical for Google Play review approval.",
    body_style
))

story.append(add_heading("6.2 IARC Content Rating", h2_style, level=1))
story.append(Paragraph(
    "The content rating questionnaire determines the age rating for your app across different regions. "
    "For NotiFetch, answer the questionnaire as follows to receive the most favorable rating:",
    body_style
))

rating_answers = [
    "Violence: None - The app contains no violent content",
    "Sexual Content: None - No sexual content of any kind",
    "Language: None - No profanity or offensive language",
    "Substance Use: None - No references to drugs, alcohol, or tobacco",
    "User Interaction: Yes - Users can receive notifications (select 'Share info' as type)",
    "Information Sharing: Yes - App sends notification data to user's own account for sync",
    "Digital Goods Purchases: No - No in-app purchases (will add Razorpay later as separate update)",
    "Simulated Gambling: None",
    "Location: No - App does not access device location",
]
for answer in rating_answers:
    story.append(Paragraph(answer, bullet_style))

story.append(Paragraph(
    "Expected rating: PEGI 3 / Everyone (lowest possible). This is important because delivery drivers "
    "of all ages use gig platforms, and a restricted rating would significantly reduce your potential user base.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 7: Legal Compliance URLs
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("7. Legal Compliance URLs", h1_style))

story.append(Paragraph(
    "Google Play requires a Privacy Policy URL for all apps, and your app includes a comprehensive "
    "legal framework. These pages are already deployed and publicly accessible on your Vercel hosting. "
    "Enter these URLs in the appropriate Play Console fields.",
    body_style
))

legal_urls_data = [
    [Paragraph('<b>Document</b>', header_cell_style),
     Paragraph('<b>URL</b>', header_cell_style),
     Paragraph('<b>Play Console Field</b>', header_cell_style)],
    [Paragraph('Privacy Policy', cell_style),
     Paragraph('https://d2-liart-nine.vercel.app/privacy', cell_style),
     Paragraph('App Content > Privacy Policy', cell_style)],
    [Paragraph('Terms of Service', cell_style),
     Paragraph('https://d2-liart-nine.vercel.app/terms', cell_style),
     Paragraph('Not required by Play, but recommended', cell_style)],
    [Paragraph('Legal Hub', cell_style),
     Paragraph('https://d2-liart-nine.vercel.app/legal', cell_style),
     Paragraph('Reference only', cell_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(legal_urls_data, [AVAILABLE_WIDTH*0.20, AVAILABLE_WIDTH*0.45, AVAILABLE_WIDTH*0.30]))

story.append(Paragraph(
    "The Privacy Policy covers India DPDP Act 2023, EU GDPR, CCPA, and Google Play Data Safety requirements. "
    "It includes sections on data collection, purpose limitation, data minimization, legal basis (GDPR Article 6), "
    "your rights (access, rectification, erasure, portability), data retention (30-day auto-delete), and "
    "grievance officer contact. The Terms of Service includes a critical 'No Affiliation' disclaimer "
    "(Section 3) and a 'Nominative Fair Use Notice' (Section 5) that protects against trademark claims "
    "from delivery platforms. These legal documents were drafted to satisfy all major privacy frameworks "
    "and Google Play's policy requirements.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 8: Upload and Review Process
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("8. Upload and Review Process", h1_style))

story.append(add_heading("8.1 Upload the AAB", h2_style, level=1))
story.append(Paragraph(
    "After completing all the above sections in Play Console, you are ready to upload your AAB. "
    "Navigate to Production > Create new release in Play Console. Upload the app-release.aab file "
    "from app/build/outputs/bundle/release/. Google Play will validate the bundle, show you the "
    "permissions it requests, and confirm the signing key. Review all the information carefully before "
    "submitting. Enter release notes for this version:",
    body_style
))

story.append(Paragraph(
    "<b>Release Notes (v2.1.0):</b><br/>"
    "- Added platform name customization: rename any delivery platform to your preferred name<br/>"
    "- Added comprehensive consent flow before data collection<br/>"
    "- Added data export and deletion (DPDP Act 2023 and GDPR compliant)<br/>"
    "- Added Privacy Policy and Terms of Service links in app<br/>"
    "- Added per-platform notification filters<br/>"
    "- Improved notification listener reliability<br/>"
    "- Enhanced data safety with network security configuration",
    body_left_style
))

story.append(add_heading("8.2 Review Timeline", h2_style, level=1))
story.append(Paragraph(
    "Google Play reviews typically take 1-7 days for new apps. Apps that access notifications or "
    "use foreground services may undergo additional scrutiny and could take up to 14 days. During "
    "the review, Google will check your app for policy compliance, malware, data safety accuracy, "
    "and content rating alignment. You can check the review status in Play Console. If your app is "
    "rejected, Google will provide specific reasons that you must address before resubmitting.",
    body_style
))

story.append(add_heading("8.3 Common Rejection Reasons for Notification Apps", h2_style, level=1))

rejection_data = [
    [Paragraph('<b>Rejection Reason</b>', header_cell_style),
     Paragraph('<b>How NotiFetch Addresses It</b>', header_cell_style)],
    [Paragraph('Missing privacy policy', cell_style),
     Paragraph('Privacy Policy is live at /privacy and linked in Play Console', cell_style)],
    [Paragraph('Unclear notification access purpose', cell_style),
     Paragraph('ConsentScreen explains what is read and why before any collection', cell_style)],
    [Paragraph('Missing data safety declarations', cell_style),
     Paragraph('Section 6 of this guide provides exact declarations', cell_style)],
    [Paragraph('Foreground service without proper type', cell_style),
     Paragraph('Manifest declares foregroundServiceType="specialUse" with PROPERTY_SPECIAL_USE_FGS_SUBTYPE', cell_style)],
    [Paragraph('Accessing data beyond stated purpose', cell_style),
     Paragraph('Only delivery partner notifications are processed; personal messages are excluded', cell_style)],
    [Paragraph('No data deletion mechanism', cell_style),
     Paragraph('In-app Delete All Data feature + web dashboard export/delete', cell_style)],
    [Paragraph('Misleading app description', cell_style),
     Paragraph('Description clearly states it reads notifications, does not claim to be a delivery platform', cell_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(rejection_data, [AVAILABLE_WIDTH*0.35, AVAILABLE_WIDTH*0.60]))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 9: Post-Submission
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("9. Post-Submission Actions", h1_style))

story.append(add_heading("9.1 Monitor Review Status", h2_style, level=1))
story.append(Paragraph(
    "After submitting, monitor your Play Console dashboard for review updates. Google will send email "
    "notifications when the review status changes. Common statuses include: 'In review' (being examined), "
    "'Ready to publish' (approved, waiting for you to publish), 'Published' (live on Play Store), and "
    "'Rejected' (issues found, must fix and resubmit). Do not make changes to the store listing while "
    "the app is in review, as this can restart the review process.",
    body_style
))

story.append(add_heading("9.2 Production Best Practices", h2_style, level=1))

post_launch = [
    "Set up Firebase Crashlytics to monitor crashes in production",
    "Enable Google Play's pre-launch reports for future versions",
    "Monitor user reviews and respond promptly to feedback",
    "Keep your Privacy Policy and Terms of Service updated",
    "Use staged rollout for future updates (start with 10% of users)",
    "Set up app signing key backup with Google Play App Signing",
    "Register a support email address for user inquiries",
    "Consider adding in-app feedback mechanism for bug reports",
]
for item in post_launch:
    story.append(Paragraph(item, bullet_style))

story.append(add_heading("9.3 Future Update Checklist", h2_style, level=1))
story.append(Paragraph(
    "For every future update, remember to: increment versionCode (must be higher than the previous "
    "release), update versionName appropriately, test the AAB on a real device before uploading, "
    "write clear release notes, and verify that any new permissions are declared in the Data Safety "
    "form. The versionCode must always be a positive integer that increases with each release. "
    "The current version is versionCode=3, versionName=2.1.0. Your next release should be "
    "versionCode=4 at minimum.",
    body_style
))

# ══════════════════════════════════════════════════════════════════════════════
# SECTION 10: Quick Reference
# ══════════════════════════════════════════════════════════════════════════════
story.extend(add_major_section("10. Quick Reference", h1_style))

quick_ref_data = [
    [Paragraph('<b>Item</b>', header_cell_style),
     Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Application ID', cell_style),
     Paragraph('com.notifetch.app', cell_style)],
    [Paragraph('Version Code', cell_style),
     Paragraph('3', cell_style)],
    [Paragraph('Version Name', cell_style),
     Paragraph('2.1.0', cell_style)],
    [Paragraph('Min SDK', cell_style),
     Paragraph('24 (Android 7.0)', cell_style)],
    [Paragraph('Target SDK', cell_style),
     Paragraph('35 (Android 15)', cell_style)],
    [Paragraph('Compile SDK', cell_style),
     Paragraph('35', cell_style)],
    [Paragraph('Keystore', cell_style),
     Paragraph('twa/keystore.jks', cell_style)],
    [Paragraph('Key Alias', cell_style),
     Paragraph('notifetch', cell_style)],
    [Paragraph('SHA-256 Fingerprint', cell_style),
     Paragraph('81:97:95:57:6B:2F:1C:94:D2:7A:6B:63:E2:3C:7C:C7:D8:58:50:CB:CA:A1:E5:00:7A:23:BB:3B:44:DD:AB:FE', cell_style)],
    [Paragraph('Privacy Policy URL', cell_style),
     Paragraph('https://d2-liart-nine.vercel.app/privacy', cell_style)],
    [Paragraph('Terms of Service URL', cell_style),
     Paragraph('https://d2-liart-nine.vercel.app/terms', cell_style)],
    [Paragraph('Play Store Category', cell_style),
     Paragraph('Productivity', cell_style)],
    [Paragraph('Content Rating', cell_style),
     Paragraph('Everyone (PEGI 3)', cell_style)],
    [Paragraph('App Signing', cell_style),
     Paragraph('Google Play App Signing (opt-in)', cell_style)],
    [Paragraph('GitHub Repository', cell_style),
     Paragraph('github.com/Yashas-K-Gangatkar/d2', cell_style)],
]
story.append(Spacer(1, 8))
story.append(make_table(quick_ref_data, [AVAILABLE_WIDTH*0.30, AVAILABLE_WIDTH*0.65]))

# ━━ Build ━━
doc.multiBuild(story)
print(f"PDF generated: {output_path}")
