#!/usr/bin/env python3
"""
NotiFetch Legal Compliance Audit - Body PDF Generator (ReportLab)
Covers: CFAA, ToS, Trademark, GDPR/CCPA, Antitrust, Labor Law, Criminal Liability, Rival Apps
"""

import os
import sys
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether,
    CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import SimpleDocTemplate

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
# Intent: neutral | Mode: minimal | Harmony: split_complementary
# Contrast: text:bg=13.67 | accent:bg=4.42
ACCENT       = colors.HexColor('#187999')
TEXT_PRIMARY  = colors.HexColor('#242527')
TEXT_MUTED    = colors.HexColor('#7d8389')
BG_SURFACE   = colors.HexColor('#e0e3e6')
BG_PAGE      = colors.HexColor('#f0f2f4')

# ReportLab table colors
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ── Page dimensions ──
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.9 * inch
BOTTOM_MARGIN = 0.9 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ── Register fonts ──
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Italic', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold', italic='LiberationSerif-Italic')
registerFontFamily('LiberationSans', normal='LiberationSans', bold='LiberationSans-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')

# ── Styles ──
styles = getSampleStyleSheet()

style_h1 = ParagraphStyle(
    name='AuditH1', fontName='LiberationSans', fontSize=18,
    leading=24, spaceBefore=18, spaceAfter=10,
    textColor=ACCENT, alignment=TA_LEFT
)
style_h2 = ParagraphStyle(
    name='AuditH2', fontName='LiberationSans', fontSize=14,
    leading=20, spaceBefore=14, spaceAfter=8,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)
style_h3 = ParagraphStyle(
    name='AuditH3', fontName='LiberationSans', fontSize=12,
    leading=17, spaceBefore=10, spaceAfter=6,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)
style_body = ParagraphStyle(
    name='AuditBody', fontName='LiberationSerif', fontSize=10.5,
    leading=17, spaceBefore=0, spaceAfter=6,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY
)
style_body_indent = ParagraphStyle(
    name='AuditBodyIndent', fontName='LiberationSerif', fontSize=10.5,
    leading=17, spaceBefore=0, spaceAfter=6,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, leftIndent=24
)
style_bullet = ParagraphStyle(
    name='AuditBullet', fontName='LiberationSerif', fontSize=10.5,
    leading=17, spaceBefore=2, spaceAfter=4,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, leftIndent=24, bulletIndent=12
)
style_quote = ParagraphStyle(
    name='AuditQuote', fontName='LiberationSerif', fontSize=10,
    leading=16, spaceBefore=6, spaceAfter=6,
    textColor=TEXT_MUTED, alignment=TA_JUSTIFY,
    leftIndent=30, rightIndent=20, borderPadding=6,
    borderColor=ACCENT, borderWidth=0, borderRadius=0
)
style_risk_high = ParagraphStyle(
    name='RiskHigh', fontName='LiberationSans', fontSize=10.5,
    leading=17, textColor=colors.HexColor('#b91c1c'), alignment=TA_CENTER
)
style_risk_low = ParagraphStyle(
    name='RiskLow', fontName='LiberationSans', fontSize=10.5,
    leading=17, textColor=colors.HexColor('#15803d'), alignment=TA_CENTER
)
style_risk_med = ParagraphStyle(
    name='RiskMed', fontName='LiberationSans', fontSize=10.5,
    leading=17, textColor=colors.HexColor('#a16207'), alignment=TA_CENTER
)
style_table_header = ParagraphStyle(
    name='TableHeader', fontName='LiberationSans', fontSize=10,
    leading=14, textColor=colors.white, alignment=TA_CENTER
)
style_table_cell = ParagraphStyle(
    name='TableCell', fontName='LiberationSerif', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_LEFT
)
style_table_cell_center = ParagraphStyle(
    name='TableCellCenter', fontName='LiberationSerif', fontSize=9.5,
    leading=14, textColor=TEXT_PRIMARY, alignment=TA_CENTER
)
style_caption = ParagraphStyle(
    name='AuditCaption', fontName='LiberationSerif', fontSize=9,
    leading=13, spaceBefore=3, spaceAfter=6,
    textColor=TEXT_MUTED, alignment=TA_CENTER
)
style_toc_h1 = ParagraphStyle(
    name='TOCHeading1', fontName='LiberationSans', fontSize=13,
    leading=20, leftIndent=20
)
style_toc_h2 = ParagraphStyle(
    name='TOCHeading2', fontName='LiberationSans', fontSize=11,
    leading=18, leftIndent=40
)
style_disclaimer = ParagraphStyle(
    name='Disclaimer', fontName='LiberationSerif', fontSize=8.5,
    leading=13, spaceBefore=4, spaceAfter=4,
    textColor=TEXT_MUTED, alignment=TA_JUSTIFY
)


# ── TOC DocTemplate ──
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def add_heading(text, style, level=0):
    import hashlib
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def make_table(data, col_ratios, caption_text=None):
    """Create a styled table with proper widths."""
    col_widths = [r * AVAILABLE_WIDTH for r in col_ratios]
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    elements = [Spacer(1, 18), t]
    if caption_text:
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(caption_text, style_caption))
    elements.append(Spacer(1, 18))
    return elements


def make_risk_box(risk_level, text):
    """Create a visually distinct risk assessment box."""
    risk_colors = {
        'NEAR ZERO': colors.HexColor('#15803d'),
        'VERY LOW': colors.HexColor('#15803d'),
        'LOW': colors.HexColor('#a16207'),
        'MEDIUM': colors.HexColor('#c2410c'),
        'HIGH': colors.HexColor('#b91c1c'),
    }
    bg_colors = {
        'NEAR ZERO': colors.HexColor('#f0fdf4'),
        'VERY LOW': colors.HexColor('#f0fdf4'),
        'LOW': colors.HexColor('#fffbeb'),
        'MEDIUM': colors.HexColor('#fff7ed'),
        'HIGH': colors.HexColor('#fef2f2'),
    }
    c = risk_colors.get(risk_level, TEXT_MUTED)
    bg = bg_colors.get(risk_level, colors.white)
    box_style = ParagraphStyle(
        name='RiskBox', fontName='Times New Roman', fontSize=11,
        leading=17, textColor=c, alignment=TA_CENTER
    )
    label_style = ParagraphStyle(
        name='RiskLabel', fontName='Times New Roman', fontSize=9,
        leading=13, textColor=TEXT_MUTED, alignment=TA_CENTER
    )
    data = [[
        Paragraph('<b>Risk Assessment</b>', style_table_header),
        Paragraph('<b>Verdict</b>', style_table_header),
        Paragraph('<b>Explanation</b>', style_table_header)
    ], [
        Paragraph(text, style_table_cell),
        Paragraph('<b>%s</b>' % risk_level, box_style),
        Paragraph('', style_table_cell)
    ]]
    col_widths = [AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.50]
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (1, 1), (1, 1), bg),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    return [Spacer(1, 12), t, Spacer(1, 12)]


# ════════════════════════════════════════════
#  BUILD DOCUMENT
# ════════════════════════════════════════════

OUTPUT_DIR = '/home/z/my-project/download'
BODY_PDF = os.path.join(OUTPUT_DIR, 'audit_body.pdf')

doc = TocDocTemplate(
    BODY_PDF,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='NotiFetch Legal Compliance Audit',
    author='Z.ai',
    creator='Z.ai',
    subject='Comprehensive legal compliance audit for NotiFetch notification aggregator application'
)

story = []

# ── Table of Contents ──
story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle(
    name='TOCTitle', fontName='LiberationSans', fontSize=20,
    leading=28, spaceBefore=12, spaceAfter=16,
    textColor=ACCENT, alignment=TA_LEFT
)))
toc = TableOfContents()
toc.levelStyles = [style_toc_h1, style_toc_h2]
story.append(toc)
story.append(PageBreak())

# ════════════════════════════════════════════
#  SECTION 1: EXECUTIVE SUMMARY
# ════════════════════════════════════════════
story.append(add_heading('<b>1. Executive Summary</b>', style_h1, level=0))
story.append(Paragraph(
    'This audit examines the legal compliance posture of <b>NotiFetch</b>, a notification aggregator '
    'application for delivery drivers. NotiFetch uses Android\'s <b>NotificationListenerService</b> API '
    'to read notifications that the user\'s phone already receives from delivery platforms (Uber Eats, '
    'DoorDash, Swiggy, etc.). The app does not access any delivery platform\'s API, does not request '
    'or store login credentials, does not use OAuth tokens, and does not scrape or crawl websites.',
    style_body
))
story.append(Paragraph(
    'The core legal question addressed is: <b>What is the probability of criminal liability for '
    'operating NotiFetch?</b> After thorough analysis across seven legal domains, this audit concludes '
    'that the probability of criminal liability is <b>NEAR ZERO</b>. The notification-listener approach '
    'represents the gold standard for legal safety in the gig-economy tool space.',
    style_body
))
story.append(Spacer(1, 6))

# Risk summary table
risk_data = [
    [Paragraph('<b>Legal Domain</b>', style_table_header),
     Paragraph('<b>Risk Level</b>', style_table_header),
     Paragraph('<b>Key Finding</b>', style_table_header)],
    [Paragraph('CFAA (Computer Fraud)', style_table_cell),
     Paragraph('<b>NEAR ZERO</b>', style_risk_low),
     Paragraph('NotificationListenerService is authorized access on user\'s own device', style_table_cell)],
    [Paragraph('Platform Terms of Service', style_table_cell),
     Paragraph('<b>VERY LOW</b>', style_risk_low),
     Paragraph('Notifications belong to the user, not the platform', style_table_cell)],
    [Paragraph('Trademark Law', style_table_cell),
     Paragraph('<b>VERY LOW</b>', style_risk_low),
     Paragraph('Nominative fair use applies; only text names used', style_table_cell)],
    [Paragraph('Data Privacy (GDPR/CCPA)', style_table_cell),
     Paragraph('<b>VERY LOW</b>', style_risk_low),
     Paragraph('Data stays on-device; Android consent built in', style_table_cell)],
    [Paragraph('Competition/Antitrust', style_table_cell),
     Paragraph('<b>NEAR ZERO</b>', style_risk_low),
     Paragraph('Complementary tool, not a competitor', style_table_cell)],
    [Paragraph('Labor Law', style_table_cell),
     Paragraph('<b>LOW</b>', style_risk_med),
     Paragraph('Productivity tool, not employer; minor auto-accept risk', style_table_cell)],
    [Paragraph('<b>Overall Criminal Liability</b>', style_table_cell),
     Paragraph('<b>NEAR ZERO</b>', style_risk_low),
     Paragraph('No viable criminal prosecution path identified', style_table_cell)],
]
col_ratios = [0.28, 0.17, 0.55]
story.extend(make_table(risk_data, col_ratios, 'Table 1: Risk Assessment Summary by Legal Domain'))

# ════════════════════════════════════════════
#  SECTION 2: CFAA ANALYSIS
# ════════════════════════════════════════════
story.append(add_heading('<b>2. CFAA (Computer Fraud and Abuse Act) Analysis</b>', style_h1, level=0))

story.append(add_heading('<b>2.1 Statutory Framework</b>', style_h2, level=1))
story.append(Paragraph(
    'The Computer Fraud and Abuse Act (18 U.S.C. 1030) criminalizes unauthorized access to protected '
    'computers. The key question for NotiFetch is whether reading notifications on a user\'s own device, '
    'with the user\'s explicit permission, constitutes "access without authorization" or "exceeding '
    'authorized access."',
    style_body
))
story.append(Paragraph(
    'NotiFetch does <b>not</b> access without authorization because: (1) the user owns the device; '
    '(2) the user grants explicit permission through Android\'s system-level notification listener '
    'permission dialog; (3) NotificationListenerService is a documented, official Android API designed '
    'for this exact purpose; and (4) the data accessed (notifications) is data the user already '
    'legitimately receives on their device.',
    style_body
))

story.append(add_heading('<b>2.2 Van Buren v. United States (2021)</b>', style_h2, level=1))
story.append(Paragraph(
    'In <i>Van Buren v. United States</i>, 593 U.S. 378 (2021), the Supreme Court adopted the '
    '"gates up or down" framework for interpreting "exceeds authorized access" under the CFAA. The '
    'Court held that an individual "exceeds authorized access" when they access a computer with '
    'authorization but then obtain information located in particular areas of the computer (such as '
    'files, folders, or databases) that are off limits to them.',
    style_body
))
story.append(Paragraph(
    'Under this framework, NotiFetch\'s access is clearly authorized because: (1) all "gates" are '
    'open -- the user has explicitly granted the notification listener permission; (2) notifications '
    'are not in an "off limits" area -- they are presented to the user by the operating system; and '
    '(3) the user is accessing their own information, not circumventing any access restriction. The '
    'Van Buren decision effectively forecloses any CFAA claim against NotiFetch.',
    style_body
))

story.append(add_heading('<b>2.3 hiQ Labs v. LinkedIn (9th Cir. 2022)</b>', style_h2, level=1))
story.append(Paragraph(
    'In <i>hiQ Labs, Inc. v. LinkedIn Corp.</i>, 31 F.4th 730 (9th Cir. 2022), the Ninth Circuit '
    'held that scraping publicly available data from LinkedIn\'s website did not constitute "access '
    'without authorization" under the CFAA. The court reasoned that since the data was publicly '
    'accessible to anyone, accessing it (even by automated means) did not violate the CFAA.',
    style_body
))
story.append(Paragraph(
    'NotiFetch\'s position is even stronger than hiQ\'s: while hiQ accessed public data on a third-party '
    'server, NotiFetch accesses data on the user\'s own device, with the user\'s explicit consent, using '
    'an API designed for that purpose. If scraping public data from a third party\'s server is not CFAA '
    'violations, then reading notifications on one\'s own device with consent is certainly not.',
    style_body
))

story.append(add_heading('<b>2.4 NotificationListenerService: Documented, Official API</b>', style_h2, level=1))
story.append(Paragraph(
    'Android\'s NotificationListenerService is an official, documented API provided by Google as part '
    'of the Android SDK. It was introduced in API Level 18 (Android 4.3) and is explicitly designed to '
    'allow applications to receive notifications from other applications. Google\'s own documentation '
    'states: "A service that receives calls from the system when new notifications are posted or removed." '
    'Using a platform-provided API for its documented purpose cannot constitute "unauthorized access" -- '
    'the platform itself authorizes and facilitates this use.',
    style_body
))

# CFAA comparison table
cfaa_data = [
    [Paragraph('<b>Case / Scenario</b>', style_table_header),
     Paragraph('<b>Access Type</b>', style_table_header),
     Paragraph('<b>CFAA Violation?</b>', style_table_header),
     Paragraph('<b>Relevance to NotiFetch</b>', style_table_header)],
    [Paragraph('<i>Van Buren</i> (2021)', style_table_cell),
     Paragraph('Authorized access, misuse of info', style_table_cell),
     Paragraph('No -- "gates up or down" test', style_table_cell_center),
     Paragraph('NotiFetch has all gates open; user grants explicit permission', style_table_cell)],
    [Paragraph('<i>hiQ v. LinkedIn</i> (2022)', style_table_cell),
     Paragraph('Scraping public data', style_table_cell),
     Paragraph('No -- public data not "unauthorized"', style_table_cell_center),
     Paragraph('NotiFetch\'s position even stronger: data on user\'s own device', style_table_cell)],
    [Paragraph('Credential-sharing apps (e.g., Para)', style_table_cell),
     Paragraph('Logging into third-party with user creds', style_table_cell),
     Paragraph('Potentially yes', style_table_cell_center),
     Paragraph('NotiFetch never uses credentials; completely different model', style_table_cell)],
    [Paragraph('<b>NotiFetch</b>', style_table_cell),
     Paragraph('Reading notifications on user\'s device via official API', style_table_cell),
     Paragraph('<b>No</b>', style_table_cell_center),
     Paragraph('Authorized, documented, consensual -- no CFAA exposure', style_table_cell)],
]
story.extend(make_table(cfaa_data, [0.22, 0.22, 0.20, 0.36], 'Table 2: CFAA Case Law Comparison'))

# ════════════════════════════════════════════
#  SECTION 3: DELIVERY PLATFORM TERMS OF SERVICE
# ════════════════════════════════════════════
story.append(add_heading('<b>3. Delivery Platform Terms of Service Analysis</b>', style_h1, level=0))

story.append(add_heading('<b>3.1 Common Platform Prohibitions</b>', style_h2, level=1))
story.append(Paragraph(
    'Most delivery platform Terms of Service (ToS) contain provisions prohibiting: (1) sharing login '
    'credentials with third parties; (2) automated API access without authorization; (3) scraping or '
    'crawling the platform\'s website or services; and (4) using bots or automation tools to interact '
    'with the platform. These provisions are designed to protect the platform\'s servers, APIs, and '
    'user accounts from unauthorized access.',
    style_body
))

story.append(add_heading('<b>3.2 Why NotiFetch Does Not Violate Platform ToS</b>', style_h2, level=1))
story.append(Paragraph(
    'NotiFetch does <b>none</b> of the prohibited activities listed above. Critically:',
    style_body
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>No credential sharing:</b> NotiFetch never asks for, receives, or stores '
    'any login credentials for any delivery platform.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>No API access:</b> NotiFetch does not call any delivery platform\'s API, '
    'whether public or private.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>No scraping or crawling:</b> NotiFetch does not access any delivery '
    'platform\'s website or servers.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>No automation of platform actions:</b> NotiFetch reads notifications '
    'that already exist on the user\'s device. It does not automate any action on the platform itself.',
    style_bullet
))

story.append(add_heading('<b>3.3 The Notification Belongs to the User</b>', style_h2, level=1))
story.append(Paragraph(
    'When a delivery platform sends a push notification to a user\'s phone, that notification is '
    'received by the user\'s operating system and displayed on the user\'s device. The notification '
    'content, once delivered, belongs to the user -- just as an email delivered to a user\'s inbox '
    'belongs to the user, regardless of who sent it. The user has every right to read, organize, '
    'and act upon their own notifications. NotiFetch simply helps them do this more efficiently.',
    style_body
))
story.append(Paragraph(
    'Courts have generally sided with users\' right to read and manage their own data. The First Sale '
    'Doctrine and personal use principles support the proposition that once data is delivered to a '
    'user\'s device, the user may process it as they see fit, provided they do not violate copyright '
    'or other specific legal protections.',
    style_body
))

story.append(add_heading('<b>3.4 Residual Risk and Mitigation</b>', style_h2, level=1))
story.append(Paragraph(
    'While the legal analysis strongly favors NotiFetch, some platforms may still attempt to claim that '
    'using a notification reader constitutes a ToS violation. This risk is mitigated by:',
    style_body
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Including clear disclaimers in the app that NotiFetch is not affiliated with, '
    'endorsed by, or connected to any delivery platform.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Terms of service within the app that clearly describe how the app works '
    'and what data it processes.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> No use of platform logos, trademarks, or trade dress -- only text names '
    'for identification purposes.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Emphasizing that users retain full control over their data at all times.',
    style_bullet
))

# ════════════════════════════════════════════
#  SECTION 4: TRADEMARK LAW
# ════════════════════════════════════════════
story.append(add_heading('<b>4. Trademark Law Analysis</b>', style_h1, level=0))

story.append(add_heading('<b>4.1 Use of Platform Names in the UI</b>', style_h2, level=1))
story.append(Paragraph(
    'NotiFetch uses the names of delivery platforms (Uber Eats, DoorDash, Swiggy, etc.) in its user '
    'interface to identify which platform generated a particular notification. This is a textbook case '
    'of <b>nominative fair use</b> -- using a trademark solely to identify the trademark owner\'s '
    'product or service, not to suggest affiliation or endorsement.',
    style_body
))

story.append(add_heading('<b>4.2 New Kids on the Block v. News America Publishing (1992)</b>', style_h2, level=1))
story.append(Paragraph(
    'The leading case on nominative fair use is <i>New Kids on the Block v. News America Publishing, '
    'Inc.</i>, 971 F.2d 302 (9th Cir. 1992). The Ninth Circuit established a three-part test for '
    'nominative fair use:',
    style_body
))
story.append(Paragraph(
    '<bullet>1.</bullet> The product or service in question must be one not readily identifiable without '
    'use of the trademark;', style_bullet
))
story.append(Paragraph(
    '<bullet>2.</bullet> Only so much of the mark or marks may be used as is reasonably necessary to '
    'identify the product or service; and', style_bullet
))
story.append(Paragraph(
    '<bullet>3.</bullet> The user must do nothing that would, in conjunction with the mark, suggest '
    'sponsorship or endorsement by the trademark holder.', style_bullet
))
story.append(Paragraph(
    'NotiFetch satisfies all three prongs: (1) delivery platforms cannot be identified without using '
    'their names; (2) NotiFetch uses only the text name, not logos or trade dress; and (3) NotiFetch '
    'includes "Not affiliated with" disclaimers and does nothing to suggest endorsement.',
    style_body
))

story.append(add_heading('<b>4.3 Mitigation Measures</b>', style_h2, level=1))
tos_data = [
    [Paragraph('<b>Measure</b>', style_table_header),
     Paragraph('<b>Implementation</b>', style_table_header),
     Paragraph('<b>Legal Basis</b>', style_table_header)],
    [Paragraph('Text names only', style_table_cell),
     Paragraph('No logos, icons, trade dress, or brand colors', style_table_cell),
     Paragraph('Nominative fair use -- minimal use of mark', style_table_cell)],
    [Paragraph('"Not affiliated with" disclaimers', style_table_cell),
     Paragraph('Displayed in app settings and about screen', style_table_cell),
     Paragraph('Prevents confusion under 15 U.S.C. 1114', style_table_cell)],
    [Paragraph('No sponsorship implication', style_table_cell),
     Paragraph('UI clearly presents NotiFetch as independent', style_table_cell),
     Paragraph('New Kids on the Block test, prong 3', style_table_cell)],
    [Paragraph('Descriptive use only', style_table_cell),
     Paragraph('Platform names used only to identify source of notifications', style_table_cell),
     Paragraph('Lanham Act 33(b)(4) descriptive fair use', style_table_cell)],
]
story.extend(make_table(tos_data, [0.25, 0.40, 0.35], 'Table 3: Trademark Risk Mitigation Measures'))

# ════════════════════════════════════════════
#  SECTION 5: DATA PRIVACY (GDPR/CCPA)
# ════════════════════════════════════════════
story.append(add_heading('<b>5. Data Privacy Analysis (GDPR / CCPA)</b>', style_h1, level=0))

story.append(add_heading('<b>5.1 Data Processing Overview</b>', style_h2, level=1))
story.append(Paragraph(
    'NotiFetch processes minimal data: notification text that is read locally on the user\'s device. '
    'The data processing flow is as follows: (1) Delivery platform sends notification to user\'s '
    'device; (2) Android OS receives notification and displays it; (3) NotiFetch\'s NotificationListenerService '
    'receives a copy of the notification; (4) Notification data stays on-device unless user explicitly '
    'opts into cloud sync. This architecture ensures data minimization by design.',
    style_body
))

story.append(add_heading('<b>5.2 GDPR Compliance</b>', style_h2, level=1))
story.append(Paragraph(
    'Under the General Data Protection Regulation (EU) 2016/679, NotiFetch\'s data processing is '
    'justified on the following grounds:',
    style_body
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Lawful basis -- Consent (Art. 6(1)(a)):</b> The user must grant the '
    'notification listener permission through Android\'s system dialog. This constitutes explicit, '
    'informed consent built into the operating system.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Data minimization (Art. 5(1)(c)):</b> Only notification text is '
    'processed -- no access to contacts, location, or other sensitive data.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Storage limitation (Art. 5(1)(e)):</b> Data stays on-device by default. '
    'Cloud sync requires explicit opt-in.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Right to erasure (Art. 17):</b> Users can delete all data at any time '
    'through the app or by revoking the notification listener permission.', style_bullet
))

story.append(add_heading('<b>5.3 CCPA Compliance</b>', style_h2, level=1))
story.append(Paragraph(
    'Under the California Consumer Privacy Act (Cal. Civ. Code 1798.100 et seq.), NotiFetch\'s '
    'compliance posture is strong:',
    style_body
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>No data sold (1798.100(a)):</b> NotiFetch does not sell personal '
    'information to any third party.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Right to delete (1798.105):</b> Users can delete their account and '
    'all associated data.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Right to know (1798.110):</b> Privacy policy clearly discloses '
    'categories of data collected and purposes.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Right to opt out (1798.120):</b> Since no data is sold, there is '
    'no "sale" to opt out of. Cloud sync is opt-in only.', style_bullet
))

# Privacy comparison table
privacy_data = [
    [Paragraph('<b>Principle</b>', style_table_header),
     Paragraph('<b>GDPR Article</b>', style_table_header),
     Paragraph('<b>CCPA Section</b>', style_table_header),
     Paragraph('<b>NotiFetch Compliance</b>', style_table_header)],
    [Paragraph('Consent / Notice', style_table_cell),
     Paragraph('Art. 6(1)(a), Art. 7', style_table_cell_center),
     Paragraph('1798.100(b)', style_table_cell_center),
     Paragraph('Android system permission dialog provides explicit consent', style_table_cell)],
    [Paragraph('Data Minimization', style_table_cell),
     Paragraph('Art. 5(1)(c)', style_table_cell_center),
     Paragraph('1798.100(e)', style_table_cell_center),
     Paragraph('Only notification text processed; no extraneous data', style_table_cell)],
    [Paragraph('Right to Delete', style_table_cell),
     Paragraph('Art. 17', style_table_cell_center),
     Paragraph('1798.105', style_table_cell_center),
     Paragraph('Users can delete all data; revoke permission', style_table_cell)],
    [Paragraph('No Data Sale', style_table_cell),
     Paragraph('Art. 6(1)(b)', style_table_cell_center),
     Paragraph('1798.100(a)', style_table_cell_center),
     Paragraph('No data sold; cloud sync is opt-in only', style_table_cell)],
    [Paragraph('Transparency', style_table_cell),
     Paragraph('Art. 13-14', style_table_cell_center),
     Paragraph('1798.110', style_table_cell_center),
     Paragraph('Clear privacy policy; data flow disclosed', style_table_cell)],
]
story.extend(make_table(privacy_data, [0.18, 0.17, 0.17, 0.48], 'Table 4: GDPR/CCPA Compliance Mapping'))

# ════════════════════════════════════════════
#  SECTION 6: COMPETITION/ANTITRUST
# ════════════════════════════════════════════
story.append(add_heading('<b>6. Competition / Antitrust Law Analysis</b>', style_h1, level=0))

story.append(add_heading('<b>6.1 Market Position</b>', style_h2, level=1))
story.append(Paragraph(
    'NotiFetch does not compete with delivery platforms -- it is a <b>complementary tool</b> that '
    'helps drivers manage notifications they already receive. NotiFetch does not: (1) offer delivery '
    'services; (2) set prices or commissions; (3) assign or route orders; (4) operate a marketplace '
    'for delivery services; or (5) displace any delivery platform\'s core business. There is no '
    'market overlap that could trigger antitrust scrutiny.',
    style_body
))

story.append(add_heading('<b>6.2 Precedent: Similar Apps Operating Successfully</b>', style_h2, level=1))
story.append(Paragraph(
    'Several similar applications have operated in the gig-economy tool space for years without '
    'antitrust issues:',
    style_body
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Mystro:</b> Uses NotificationListenerService to aggregate ride-share '
    'and delivery notifications. Operating since 2017 without antitrust challenges.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Maxymo:</b> Uses NotificationListenerService for ride-share drivers. '
    'Continues to operate successfully.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> <b>Para:</b> Initially used credential sharing (logging into platforms '
    'with user credentials), was sued by Uber, and was forced to pivot to the notification-listener '
    'approach. This contrast is instructive.', style_bullet
))
story.append(Paragraph(
    'No market manipulation, price fixing, or exclusionary practices are present. Risk of antitrust '
    'liability is <b>NEAR ZERO</b>.',
    style_body
))

# ════════════════════════════════════════════
#  SECTION 7: LABOR LAW
# ════════════════════════════════════════════
story.append(add_heading('<b>7. Labor Law Analysis</b>', style_h1, level=0))

story.append(add_heading('<b>7.1 NotiFetch Is Not an Employer</b>', style_h2, level=1))
story.append(Paragraph(
    'NotiFetch does not employ drivers, set wages, assign work, control schedules, or direct the '
    'manner in which drivers perform their duties. It is a <b>productivity tool</b> -- analogous '
    'to a calendar app that helps a freelancer manage appointments. Labor law typically applies to '
    'entities that exercise control over workers\' employment conditions, which NotiFetch does not.',
    style_body
))

story.append(add_heading('<b>7.2 Auto-Accept Feature: The One Area of Caution</b>', style_h2, level=1))
story.append(Paragraph(
    'If NotiFetch offers an auto-accept feature (automatically accepting delivery offers based on '
    'user-defined criteria), some jurisdictions may view this as concerning because: (1) it could be '
    'seen as automating a worker\'s acceptance of terms or conditions; (2) platform ToS may prohibit '
    'automated acceptance of offers; and (3) regulators could theoretically argue that auto-accept '
    'tools facilitate "algorithmic management" of gig workers.',
    style_body
))

story.append(add_heading('<b>7.3 Mitigation</b>', style_h2, level=1))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Make auto-accept <b>optional</b> and clearly disclose that it is an '
    'experimental feature.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Include prominent disclaimers that the user remains solely responsible '
    'for all delivery acceptances.', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Require explicit user configuration (no default auto-accept).', style_bullet
))
story.append(Paragraph(
    '<bullet>&bull;</bullet> Monitor regulatory developments in key jurisdictions (California, EU, '
    'UK) regarding gig-economy automation tools.', style_bullet
))

# ════════════════════════════════════════════
#  SECTION 8: CRIMINAL LIABILITY VERDICT
# ════════════════════════════════════════════
story.append(add_heading('<b>8. Criminal Liability Verdict</b>', style_h1, level=0))

story.append(add_heading('<b>8.1 Probability Assessment</b>', style_h2, level=1))
story.append(Paragraph(
    'After comprehensive analysis across all seven legal domains, this audit concludes that the '
    'probability of criminal liability for operating NotiFetch is <b>NEAR ZERO</b>. The analysis '
    'is based on the following reasoning:',
    style_body
))

# Verdict table
verdict_data = [
    [Paragraph('<b>Factor</b>', style_table_header),
     Paragraph('<b>Analysis</b>', style_table_header)],
    [Paragraph('CFAA exposure', style_table_cell),
     Paragraph('No unauthorized access; user grants explicit permission via Android system dialog; '
               'NotificationListenerService is a documented official API. Van Buren and hiQ decisions '
               'foreclose CFAA claims.', style_table_cell)],
    [Paragraph('Platform ToS claims', style_table_cell),
     Paragraph('Even if a platform claims ToS violation, this is a <b>civil</b> matter, not criminal. '
               'The user reads their own notifications -- no hacking, no unauthorized server access.', style_table_cell)],
    [Paragraph('Trademark claims', style_table_cell),
     Paragraph('Nominative fair use is well-established law. Using text names to identify platforms '
               'is not trademark infringement. This is a civil matter, not criminal.', style_table_cell)],
    [Paragraph('Data theft', style_table_cell),
     Paragraph('No data is stolen. The notification is delivered to the user\'s device by the platform '
               'itself. The user reads their own data.', style_table_cell)],
    [Paragraph('Wire fraud / mail fraud', style_table_cell),
     Paragraph('No scheme to defraud exists. NotiFetch provides a legitimate service that helps users '
               'manage their own notifications.', style_table_cell)],
]
story.extend(make_table(verdict_data, [0.22, 0.78], 'Table 5: Criminal Liability Factor Analysis'))

story.append(add_heading('<b>8.2 The Notification-Listener Gold Standard</b>', style_h2, level=1))
story.append(Paragraph(
    'The notification-listener approach is the <b>gold standard</b> for legal safety in the gig-economy '
    'tool space. This is not merely theoretical -- it has been validated by years of successful operation '
    'by apps like Mystro and Maxymo, and by the cautionary tale of Para (which was sued for using '
    'credential sharing and forced to pivot to the notification-listener approach).',
    style_body
))

story.append(add_heading('<b>8.3 Recommendations</b>', style_h2, level=1))
story.append(Paragraph(
    '<bullet>1.</bullet> <b>File an intent-to-use trademark application</b> for "NotiFetch" in '
    'Class 009 (software) and Class 042 (SaaS) with the USPTO to protect the brand.', style_bullet
))
story.append(Paragraph(
    '<bullet>2.</bullet> <b>Budget for legal counsel</b> familiar with CFAA and gig-economy law. '
    'While the risk is near zero, having counsel on retainer provides peace of mind and rapid response '
    'capability if a platform sends a cease-and-desist letter.', style_bullet
))
story.append(Paragraph(
    '<bullet>3.</bullet> <b>Maintain the notification-listener approach</b> and never add credential '
    'sharing, API access, or scraping features. The Para case demonstrates the critical importance '
    'of this architectural decision.', style_bullet
))
story.append(Paragraph(
    '<bullet>4.</bullet> <b>Implement robust disclaimers</b> throughout the app: "Not affiliated with," '
    '"Not endorsed by," and "Independent tool" language.', style_bullet
))
story.append(Paragraph(
    '<bullet>5.</bullet> <b>Monitor regulatory developments</b> in key jurisdictions regarding '
    'gig-economy tools and notification access.', style_bullet
))

# ════════════════════════════════════════════
#  SECTION 9: COMPARISON WITH RIVAL APPS
# ════════════════════════════════════════════
story.append(add_heading('<b>9. Comparison with Rival Apps</b>', style_h1, level=0))

story.append(add_heading('<b>9.1 Detailed Comparative Analysis</b>', style_h2, level=1))
story.append(Paragraph(
    'The following table provides a detailed comparison of NotiFetch with key rival applications in '
    'the gig-economy tool space. The contrast between notification-listener apps and credential-sharing '
    'apps is the most important takeaway from this audit.',
    style_body
))

rival_data = [
    [Paragraph('<b>App</b>', style_table_header),
     Paragraph('<b>Access Method</b>', style_table_header),
     Paragraph('<b>Legal Outcome</b>', style_table_header),
     Paragraph('<b>Current Status</b>', style_table_header),
     Paragraph('<b>Key Lesson</b>', style_table_header)],
    [Paragraph('<b>NotiFetch</b>', style_table_cell),
     Paragraph('Notification Listener', style_table_cell_center),
     Paragraph('No legal issues', style_table_cell_center),
     Paragraph('In development', style_table_cell_center),
     Paragraph('Gold standard approach', style_table_cell)],
    [Paragraph('Mystro', style_table_cell),
     Paragraph('Notification Listener', style_table_cell_center),
     Paragraph('No legal issues', style_table_cell_center),
     Paragraph('Operating since 2017', style_table_cell_center),
     Paragraph('Proof of concept: notification listener is safe', style_table_cell)],
    [Paragraph('Maxymo', style_table_cell),
     Paragraph('Notification Listener', style_table_cell_center),
     Paragraph('No legal issues', style_table_cell_center),
     Paragraph('Operating successfully', style_table_cell_center),
     Paragraph('Further validation of the approach', style_table_cell)],
    [Paragraph('Para', style_table_cell),
     Paragraph('Credential sharing (used to)', style_table_cell_center),
     Paragraph('<b>Sued by Uber</b>', style_table_cell_center),
     Paragraph('Forced to pivot to notification listener', style_table_cell_center),
     Paragraph('Credential sharing = legal danger', style_table_cell)],
]
story.extend(make_table(rival_data, [0.12, 0.18, 0.18, 0.22, 0.30], 'Table 6: Rival App Comparison'))

story.append(add_heading('<b>9.2 The Para Case: A Cautionary Tale</b>', style_h2, level=1))
story.append(Paragraph(
    'Para\'s experience is the most instructive case study in this space. Para originally asked users '
    'for their Uber, Lyft, and DoorDash login credentials, then used those credentials to log into '
    'the platforms on the user\'s behalf. This approach triggered a lawsuit from Uber, which alleged '
    'that Para\'s access violated its Terms of Service and potentially the CFAA. Para was forced to '
    'settle and pivot to the notification-listener approach.',
    style_body
))
story.append(Paragraph(
    'The key distinction is clear: <b>credential sharing = legal danger; notification listening = legal '
    'safety.</b> NotiFetch was designed from the ground up using the notification-listener approach, '
    'avoiding the legal pitfalls that trapped Para.',
    style_body
))

# Decision matrix
story.append(add_heading('<b>9.3 Legal Safety Decision Matrix</b>', style_h2, level=1))
matrix_data = [
    [Paragraph('<b>Approach</b>', style_table_header),
     Paragraph('<b>CFAA Risk</b>', style_table_header),
     Paragraph('<b>ToS Risk</b>', style_table_header),
     Paragraph('<b>Privacy Risk</b>', style_table_header),
     Paragraph('<b>Overall</b>', style_table_header)],
    [Paragraph('Notification Listener (NotiFetch, Mystro, Maxymo)', style_table_cell),
     Paragraph('None', style_table_cell_center),
     Paragraph('Minimal', style_table_cell_center),
     Paragraph('Minimal', style_table_cell_center),
     Paragraph('<b>SAFE</b>', style_table_cell_center)],
    [Paragraph('Credential Sharing (old Para)', style_table_cell),
     Paragraph('High', style_table_cell_center),
     Paragraph('High', style_table_cell_center),
     Paragraph('High', style_table_cell_center),
     Paragraph('<b>DANGEROUS</b>', style_table_cell_center)],
    [Paragraph('API Scraping', style_table_cell),
     Paragraph('Moderate-High', style_table_cell_center),
     Paragraph('High', style_table_cell_center),
     Paragraph('Moderate', style_table_cell_center),
     Paragraph('<b>RISKY</b>', style_table_cell_center)],
    [Paragraph('Official API Partnership', style_table_cell),
     Paragraph('None', style_table_cell_center),
     Paragraph('None', style_table_cell_center),
     Paragraph('Low', style_table_cell_center),
     Paragraph('<b>IDEAL (but impractical)</b>', style_table_cell_center)],
]
story.extend(make_table(matrix_data, [0.30, 0.15, 0.15, 0.15, 0.25], 'Table 7: Legal Safety Decision Matrix'))

# ════════════════════════════════════════════
#  SECTION 10: DISCLAIMER
# ════════════════════════════════════════════
story.append(Spacer(1, 24))
story.append(HRFlowable(width="100%", thickness=0.5, color=TEXT_MUTED, spaceAfter=12))
story.append(Paragraph(
    '<b>Disclaimer:</b> This audit is provided for informational purposes only and does not constitute '
    'legal advice. The analysis is based on current law as of March 2026 and may be subject to change '
    'through legislative action, judicial decisions, or regulatory guidance. NotiFetch should consult '
    'with a qualified attorney familiar with CFAA, gig-economy law, and data privacy regulations '
    'before making any business decisions based on this analysis. Past outcomes in similar cases do '
    'not guarantee future results.',
    style_disclaimer
))

# ── Build ──
doc.multiBuild(story)
print(f"Body PDF generated: {BODY_PDF}")
